//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSpecTester.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"03 F2 00 00 00 02 00 00 00 6A 00 03 00 00 00 00 
00 00 00 00 00 00 01 00 00 00 00 00 57 03 F2 00 
00 00 57 00 15 00 00 18 86 03 00 00 00 2B 00 00 
00 00 00 00 0A 31 32 33 34 35 36 37 38 39 30 01 
01 00 00 65 56 34 00 00 00 00 0C 0C 01 00 0C 00 
00 00 01 20 00 0A 30 2C 31 2C 2D 31 2C 32 35 36 
00 F0 01 40 01 00 00 0C 68 74 74 70 3A 2F 2F 30 
2E 68 74 6D")]
        public string RequestHex {
            get {
                return ((string)(this["RequestHex"]));
            }
            set {
                this["RequestHex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03 F2 00 00 03 A3 00 00 0C 52 00 13 33 31 35 34 \r\n3A 32 30 31 30 30 31 30 37 30 3" +
            "9 31 36 30 36 00 \r\n00 00 00 00 00 00 00 00 01 01 00 0C 68 74 74 70 \r\n3A 2F 2F 30" +
            " 2E 68 74 6D 00 0C 68 74 74 70 3A 2F \r\n2F 30 2E 68 74 6D 00 00 00 00 03 5B 3C 68" +
            " 74 6D \r\n6C 3E 3C 68 65 61 64 3E 3C 6D 65 74 61 20 68 74 \r\n74 70 2D 65 71 75 69 " +
            "76 3D 22 43 6F 6E 74 65 6E \r\n74 2D 54 79 70 65 22 20 63 6F 6E 74 65 6E 74 3D \r\n2" +
            "2 74 65 78 74 2F 68 74 6D 6C 3B 20 63 68 61 72 \r\n73 65 74 3D 75 74 66 2D 38 22 3" +
            "E 3C 74 69 74 6C \r\n65 3E E5 AF BC E8 88 AA E9 A1 B5 E9 9D A2 3C 2F \r\n74 69 74 6C" +
            " 65 3E 3C 2F 68 65 61 64 3E 3C 62 6F \r\n64 79 3E 3C 61 20 68 72 65 66 3D 22 2F 6C" +
            " 65 73 \r\n6F 75 2F 69 6E 64 65 78 2E 61 73 70 78 22 20 75 \r\n6E 64 65 72 6C 69 6E " +
            "65 3D 22 30 22 3E E4 B9 90 \r\nE6 90 9C 3C 2F 61 3E 7C 3C 61 20 68 72 65 66 3D \r\n2" +
            "2 2F 31 31 34 2F 69 6E 64 65 78 2E 61 73 70 78 \r\n22 20 75 6E 64 65 72 6C 69 6E 6" +
            "5 3D 22 30 22 3E \r\n31 31 34 3C 2F 61 3E 7C 3C 61 20 68 72 65 66 3D \r\n22 2F 6F 74" +
            " 68 65 72 2F 66 61 76 6C 69 73 74 2E \r\n61 73 70 78 22 20 75 6E 64 65 72 6C 69 6E" +
            " 65 3D \r\n22 30 22 3E E6 94 B6 E8 97 8F 3C 2F 61 3E 3C 62 \r\n72 3E 3C 61 20 68 72 " +
            "65 66 3D 22 2F 6F 74 68 65 \r\n72 2F 6F 72 64 65 72 6C 69 73 74 2E 61 73 70 78 \r\n2" +
            "2 20 75 6E 64 65 72 6C 69 6E 65 3D 22 30 22 3E \r\nE8 AE A2 E5 8D 95 3C 2F 61 3E 7" +
            "C 3C 61 20 68 72 \r\n65 66 3D 22 2F 61 69 72 2F 69 6E 64 65 78 2E 61 \r\n73 70 78 22" +
            " 20 75 6E 64 65 72 6C 69 6E 65 3D 22 \r\n30 22 3E E6 9C BA E7 A5 A8 3C 2F 61 3E 7C" +
            " 3C 61 \r\n20 68 72 65 66 3D 22 2F 68 6F 74 65 6C 2F 69 6E \r\n64 65 78 2E 61 73 70 " +
            "78 22 20 75 6E 64 65 72 6C \r\n69 6E 65 3D 22 30 22 3E E9 85 92 E5 BA 97 3C 2F \r\n6" +
            "1 3E 3C 62 72 3E 3C 61 20 68 72 65 66 3D 22 2F \r\n66 6F 6F 64 2F 69 6E 64 65 78 2" +
            "E 61 73 70 78 22 \r\n20 75 6E 64 65 72 6C 69 6E 65 3D 22 30 22 3E E7 \r\nBE 8E E9 A3" +
            " 9F 3C 2F 61 3E 7C 3C 61 20 68 72 65 \r\n66 3D 22 2F 74 72 61 76 65 6C 2F 69 6E 64" +
            " 65 78 \r\n2E 61 73 70 78 22 20 75 6E 64 65 72 6C 69 6E 65 \r\n3D 22 30 22 3E E6 97 " +
            "85 E6 B8 B8 3C 2F 61 3E 7C \r\n3C 61 20 68 72 65 66 3D 22 2F 73 68 69 62 6F 2F \r\n6" +
            "9 6E 64 65 78 2E 61 73 70 78 22 20 75 6E 64 65 \r\n72 6C 69 6E 65 3D 22 30 22 3E E" +
            "4 B8 96 E5 8D 9A \r\nE7 A5 A8 3C 2F 61 3E 3C 62 72 3E 3C 61 20 68 72 \r\n65 66 3D 22" +
            " 2F 6F 74 68 65 72 2F 68 65 6C 70 2E \r\n61 73 70 78 22 20 75 6E 64 65 72 6C 69 6E" +
            " 65 3D \r\n22 30 22 3E E5 B8 AE E5 8A A9 3C 2F 61 3E 7C 3C \r\n61 20 68 72 65 66 3D " +
            "22 2F 63 61 72 64 2F 69 6E \r\n64 65 78 2E 61 73 70 78 22 20 75 6E 64 65 72 6C \r\n6" +
            "9 6E 65 3D 22 30 22 3E E7 82 B9 E5 8D A1 3C 2F \r\n61 3E 7C 3C 61 20 68 72 65 66 3" +
            "D 22 2F 70 61 79 \r\n2F 69 6E 64 65 78 2E 61 73 70 78 22 20 75 6E 64 \r\n65 72 6C 69" +
            " 6E 65 3D 22 30 22 3E E4 BB 98 E8 B4 \r\nB9 E9 80 9A 3C 2F 61 3E 3C 62 72 3E 3C 61" +
            " 20 68 \r\n72 65 66 3D 22 2F 62 6F 6F 6B 2F 62 6F 6F 6B 64 \r\n65 74 61 69 6C 2E 68 " +
            "74 6D 6C 22 20 75 6E 64 65 \r\n72 6C 69 6E 65 3D 22 30 22 3E E6 9E 81 E5 93 81 \r\nE" +
            "7 94 B5 E5 AD 90 E4 B9 A6 E6 B5 8B E8 AF 95 E9 \r\nA1 B5 E9 9D A2 3C 2F 61 3E 3C 2" +
            "F 62 6F 64 79 3E \r\n3C 2F 68 74 6D 6C 3E 00 00")]
        public string ResponseHex {
            get {
                return ((string)(this["ResponseHex"]));
            }
            set {
                this["ResponseHex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HexAsciiView {
            get {
                return ((string)(this["HexAsciiView"]));
            }
            set {
                this["HexAsciiView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cbxParseType")]
        public string HexParseType {
            get {
                return ((string)(this["HexParseType"]));
            }
            set {
                this["HexParseType"] = value;
            }
        }
    }
}
